### ISSUE TITLE
Add usage

### ISSUE THREAD

**Issue by KRYPTOHAUS** [ipld/js-ipld-torrent-file#2]
Please :)

**Comment by daviddias** [comment]
Absolutely @KRYPTOHAUS, love the excitement!

I had to put this work on the side as I finish all things [DAG Api](https://github.com/ipfs/interface-ipfs-core/pull/123), will come back at it this week.

Meanwhile, you can track the development by this main issue https://github.com/ipfs/js-ipfs/issues/779, I'll use it as a log :)

**Comment by rvagg** [comment]
closing for archival
